# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: README.*.md
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
  # for Terraform
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0 # https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - "--args=-json"
          - "--args=-no-color"
      - id: terraform_tflint
      - id: terraform_tfsec
  # for go
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --config=.golangci.yaml
        types: [go]
        language: golang
        exclude: ^.*_test.go$
        pass_filenames: false
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    - id: detect-secrets
        # args: ['--baseline', '.secrets.baseline']
        # exclude: package.lock.json
-   repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.0
    hooks:
    -   id: gitleaks
