# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: ci-push-dev
on:
  push:
    branches:
      - "feature/**"
      - "develop"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "terraform: integration"
        env:
          ENV: ${{ secrets.ENV_DEV }}
        run: |
          echo "$ENV" >> $PWD/.env
          chmod +x scripts/*
          docker pull ghcr.io/y-miyazaki/terraform-aws:latest
          docker run --rm -v $PWD:/workspace --env-file=$PWD/.env -w /workspace --name terraform-aws ghcr.io/y-miyazaki/terraform-aws:latest scripts/integration.sh terraform
      - name: "slack: notification for failed integration."
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: failed integration on push
          SLACK_USERNAME: github-notification
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
