# CI workflow: Shell script lint on push/PR
name: on-ci-push-shell-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - "**/*.bats"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - "**/*.bats"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  shell-script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-shell-script.yaml@ebb7197da8cf5306a36dc5a865cf7c4519bad6dd # v1.8.38
    with:
      script_path: "**/*.sh,**/*.bats"
    permissions:
      checks: write
      contents: read
      pull-requests: write
