# CI workflow: Shell script lint on push/PR
name: on-ci-push-shell-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - "**/*.bats"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - "**/*.bats"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  shell-script-ci:
    uses: y-miyazaki/config/.github/workflows/ci-shell-script.yaml@b2e71e5b0feb7ddb913ff8d2e82224b5dcdbfeae # v1.8.75
    with:
      run_shell_tests: true
      script_path: "**/*.sh,**/*.bats"
    permissions:
      checks: write
      contents: read
      pull-requests: write
