# Manual workflow: ECS deployment (application, dev)
name: on-cd-wd-application-ecs-dev

on:
  workflow_dispatch: # Manual deployment workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  ecs-deploy:
    permissions:
      contents: read
      id-token: write
    uses: y-miyazaki/config/.github/workflows/cd-aws-ecs.yaml@b41047b74f8f4a06ca37866f9aaa2e919565079c # v1.8.81
    with:
      ecs_service_base_dir: "ecs/ecs-service/test-server"
      environment: "dev"
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
