# CI workflow: Node.js CI on push/PR
name: on-ci-push-nodejs

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  nodejs-ci:
    uses: y-miyazaki/config/.github/workflows/ci-nodejs.yaml@e8e7b4c4a5b67c33331236d77a3fb4dfa6c7706f # v1.8.64
    with:
      search_paths: nodejs
    permissions:
      contents: read
      id-token: write
      pull-requests: write
