# CI workflow: Node.js CI on push/PR
name: on-ci-push-nodejs

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  nodejs-ci:
    uses: y-miyazaki/config/.github/workflows/ci-nodejs.yaml@641b6fd43c2e86a06f68aebb2b3882a68f9a0772 # v1.8.69
    with:
      search_paths: nodejs
    permissions:
      contents: read
      id-token: write
      pull-requests: write
