# CI workflow: Markdown lint on push/PR
name: on-ci-push-markdown

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdown-link-check.json"
      - ".markdownlint-cli2.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdown-link-check.json"
      - ".markdownlint-cli2.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  markdown-ci:
    uses: y-miyazaki/config/.github/workflows/ci-markdown.yaml@23e5cf3067e2caa53307b6f49d88545bd74af7f5 # v1.8.74
    permissions:
      contents: read
      pull-requests: write
