# CI workflow: Node.js CI on push/PR
name: on-ci-push-nodejs

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "nodejs/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  nodejs-ci:
    uses: y-miyazaki/config/.github/workflows/ci-nodejs.yaml@d0cc8a35c10dda4f7ad626a87bfc145e08a6149b # v1.8.83
    with:
      search_paths: nodejs
    permissions:
      contents: read
      id-token: write
      pull-requests: write
