# CI workflow: GitHub Actions workflow lint on push/PR
name: on-ci-push-github-actions-workflow

on:
    push:
        branches:
            - "main"
            - "master"
            - "hotfix/**"
            - "release/**"
            - "develop"
            - "feature/**"
        paths:
            - ".github/workflows/**/*.yml"
            - ".github/workflows/**/*.yaml"
            - ".github/actions/**/*.yml"
            - ".github/actions/**/*.yaml"
            - "**/action.yml"
            - "**/action.yaml"
    pull_request:
        branches:
            - "main"
            - "master"
            - "hotfix/**"
            - "release/**"
            - "develop"
            - "feature/**"
        paths:
            - ".github/workflows/**/*.yml"
            - ".github/workflows/**/*.yaml"
            - ".github/actions/**/*.yml"
            - ".github/actions/**/*.yaml"
            - "**/action.yml"
            - "**/action.yaml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    github-actions-workflow-ci:
        uses: y-miyazaki/config/.github/workflows/ci-github-actions-workflow.yaml@2f6b2763e61567e4a57e42d8bed8e16f1b5b39fe # v1.7.3
        permissions:
            contents: read
