# CI workflow for Markdown files
name: on-ci-push-markdown

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdownlint.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdownlint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-ci:
    uses: y-miyazaki/config/.github/workflows/ci-markdown.yaml@051f9d105a245f5fc4760059e96a3f1d586c5d82 # v1.0.5
    permissions:
      contents: read
      pull-requests: write
