# CD workflow: Build and deploy MkDocs to GitHub Pages
name: on-cd-mkdocs

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    uses: ./.github/workflows/cd-mkdocs.yaml
    with:
      artifact_name: mkdocs-site
      config_file: mkdocs.yml
    permissions:
      contents: read

  deploy:
    needs: build
    uses: ./.github/workflows/cd-github-pages.yaml
    with:
      artifact_name: mkdocs-site
    permissions:
      contents: read
      id-token: write
      pages: write
