# CI workflow for Markdown files
name: on-ci-push-markdown

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/on-ci-push-markdown.yaml"
      - ".github/workflows/ci-markdown.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.md"
      - "docs/**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/on-ci-push-markdown.yaml"
      - ".github/workflows/ci-markdown.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-ci:
    uses: ./.github/workflows/ci-markdown.yaml
    permissions:
      contents: read
      pull-requests: write
